# Generated by Django 3.1.5 on 2021-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('AA', 'Addis Ababa'), ('AF', 'Afar'), ('AM', 'Amhara'), ('BN', 'Benishangul-Gumuz'), ('DD', 'Dire Dawa'), ('GM', 'Gambela'), ('HR', 'Harari'), ('Or', 'Oromiya'), ('SD', 'Sidama'), ('SNNP', 'Southern Nations, Nationalities, and Peoples'), ('TG', 'Tigray')], max_length=4, null=True),
        ),
    ]
