# Generated by Django 3.1.5 on 2021-04-26 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20210411_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-/]+\\Z', message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
