# Generated by Django 3.1.5 on 2021-04-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20210402_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='media/profile_picture/%y%m%d'),
            preserve_default=False,
        ),
    ]
