# Generated by Django 3.1.6 on 2021-04-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YearOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='images/face_datas')),
                ('id_n', models.CharField(max_length=12, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cafe_status', models.CharField(choices=[('C', 'Cafe'), ('NC', 'None Cafe')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('region', models.CharField(choices=[('AA', 'Addis Ababa'), ('AF', 'Afar'), ('AM', 'Amhara'), ('BN', 'Benishangul-Gumuz'), ('DD', 'Dire Dawa'), ('GM', 'Gambela'), ('HR', 'Harari'), ('Or', 'Oromiya'), ('SD', 'Sidama'), ('SNNP', 'Southern Nations, Nationalities, and Peoples'), ('TG', 'Tigray')], max_length=4)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facex.department')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facex.fieldofstudy')),
            ],
        ),
    ]
