# Generated by Django 3.1.5 on 2021-04-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLog',
        ),
    ]
