# Generated by Django 3.1.5 on 2021-04-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
        migrations.DeleteModel(
            name='YearOfStudy',
        ),
    ]
