# Generated by Django 3.1.6 on 2021-04-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='facex.yearofstudy'),
            preserve_default=False,
        ),
    ]
