# Generated by Django 3.1.5 on 2021-04-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cafe_status',
            field=models.CharField(choices=[('C', 'Cafe'), ('NC', 'C')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
