# Generated by Django 3.1.5 on 2021-04-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0002_auto_20210403_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.CharField(max_length=200)),
            ],
        ),
    ]
