# Generated by Django 3.1.5 on 2021-04-06 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0006_studentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlog',
            name='date',
        ),
        migrations.AddField(
            model_name='studentlog',
            name='date_l',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
