# Generated by Django 3.1.5 on 2021-04-06 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0007_auto_20210406_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlog',
            name='date_l',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
