# Generated by Django 3.1.5 on 2021-04-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0008_auto_20210406_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlog',
            old_name='date_l',
            new_name='date',
        ),
    ]
