# Generated by Django 3.1.5 on 2021-04-09 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facex', '0010_auto_20210408_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='school_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facex.schoolprogram'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='school_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facex.schoolprogram'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facex.schoolprogram'),
        ),
    ]
