# Generated by Django 3.1.5 on 2021-04-09 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facex', '0011_auto_20210409_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users_app.userprofile'),
            preserve_default=False,
        ),
    ]
