# Generated by Django 3.1.5 on 2021-04-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facex', '0012_auto_20210409_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
